version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_HOST: <endpoint do bd>
      MYSQL_ROOT_PASSWORD: senha do banco
      MYSQL_DATABASE: nome do banco
      MYSQL_USER: user do banco
      MYSQL_PASSWORD: senha do usuario
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user do banco
      WORDPRESS_DB_PASSWORD: senha do banco
      WORDPRESS_DB_NAME: nome do banco
    volumes:
      ["mnt/docker/docker:/var/www/html"]
volumes:
  mysql: {}
